firstlaunch: true
data:
  maxref: 9
  moneyb: b
  msgmax: ne peux pas avoir de filleuls supplementaires !
  isref: Vous avez atteint le nombre maximal de parrains !
  hasask: a deja recu votre demande !
  fhasp: a deja un parrain !
  noask: ne vous a pas envoyer de demande !
  accp: est devenu votre parrain !
  accf: est devenu votre filleul !
  refp: a refuse de devenir votre parrain !
  reff: Vous avez refuse la demande de
  nof: Vous n'avez pas de filleul !
db:
  host: localhost
  port: 3306
  database: sponso
  username: root
  password: ""
 
advancement:
  - minecraft:adventure/adventuring_time
  - minecraft:adventure/arbalistic
  - minecraft:adventure/hero_of_the_village
  - minecraft:adventure/honey_block_slide
  - minecraft:adventure/kill_a_mob
  - minecraft:adventure/shoot_arrow
  - minecraft:adventure/ol_betsy
  - minecraft:adventure/root
  - minecraft:adventure/shoot_arrow
  - minecraft:adventure/summon_iron_golem
rewards:
  minecraft:adventure/adventuring_time: 10
  minecraft:adventure/arbalistic: 20
  minecraft:adventure/hero_of_the_village: 30
  minecraft:adventure/honey_block_slide: 40
  minecraft:adventure/kill_a_mob: 50
  minecraft:adventure/shoot_arrow: 60
  minecraft:adventure/ol_betsy: 70
  minecraft:adventure/root: 80
  minecraft:adventure/shoot_arrow: 90
  minecraft:adventure/summon_iron_golem: 100
