name: BreakerReferral
main: com.azod.referral.main
api-version: 1.15
version: 1.0
description: Referral a player
author: AzodFR
depends: [Vault]

commands:
  parrain:
    description: choose your sponsor