name: BreakerReferral
main: com.azod.referral.main
api-version: 1.15
version: 1.2
description: Referral a player
author: AzodFR
depends: [Vault]

commands:
  parrain:
    description: Choisissez un parrain
  padv:
    description: Alias de parrain advancement
permissions:
  parrain.admin:
    description: for reload the config
permission-message: You not have have permission to use this command.